/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 apart.glb -T -S
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vr-apartment-loft-interior-baked-54bc929a26094b6cb36f977903fbcd97
Title: VR apartment loft interior | baked
*/
import { Html, useGLTF } from "@react-three/drei";

export default function Apart(props) {
  const { nodes, materials } = useGLTF("/apart-transformed.glb");
  const { setHovered } = props;
  return (
    <group
    
      {...props}
      dispose={null}
      rotation={[0, -Math.PI / 1.8, 0]}
      position={[0, -1.4, 1]}
    >
      <group scale={0.01}>
        <mesh
          geometry={nodes["Stairs_���������10003_0"].geometry}
          material={materials["10.003"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 110.28]}
        />
        <mesh
          geometry={nodes["House_���������10_0"].geometry}
          material={materials.material}
          position={[115.14, 409.63, -276.93]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[409.82, 566.2, 409.82]}
        />
        <mesh
          geometry={nodes["2nd_floor_���������10001_0"].geometry}
          material={materials["10.001"]}
          position={[230.76, 405.98, -470.33]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[290.07, 367.83, 9.15]}
        />
        <mesh
          geometry={nodes["floor_���������10002_0"].geometry}
          material={materials["10.002"]}
          position={[115.14, -3.5, -107.31]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[409.82, 566.2, 409.82]}
        />
        <mesh
          geometry={nodes.Window_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[115.14, 409.63, -169.04]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[409.82, 566.2, 409.82]}
        />
        <group
          onPointerEnter={() => setHovered(true)}
          onPointerLeave={() => setHovered(false)}
        >
          <mesh
            geometry={nodes.Sphere_Material002_0.geometry}
            material={materials["Material.002"]}
            position={[0, 306.18, 74.71]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[-7.83, 7.83, 7.83]}
          >
            <Html prepend wrapperClass="light">
              Light
            </Html>
          </mesh>
          <mesh
            geometry={nodes.lighting_Material004_0.geometry}
            material={materials["Material.004"]}
            position={[0, 229.87, 10.87]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[33.78, 20.83, 33.78]}
          />
        </group>
        <mesh
          geometry={nodes.Sphere001_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[0, 217.82, 10.87]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-7.83, 7.83, 7.83]}
        />
        <mesh
          geometry={nodes["2nd_floor_lighting_Material006_0"].geometry}
          material={materials["Material.002"]}
          position={[230.76, 405.98, -470.33]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[290.07, 367.83, 9.15]}
        ></mesh>
        <mesh
          geometry={nodes.outside_Material009_0.geometry}
          material={materials["Material.009"]}
          position={[-654.4, 99.5, -442.7]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={[478.37, 292.06, 478.37]}
        ></mesh>
        <mesh
          onPointerEnter={() => setHovered(true)}
          onPointerLeave={() => setHovered(false)}
          geometry={nodes.painting_Material010_0.geometry}
          material={materials["Material.010"]}
          position={[-95.42, 138.41, -478.87]}
          rotation={[-1.72, 0, 0]}
          scale={[70.79, 3.49, 138.03]}
        >
          <Html prepend wrapperClass="painting">
            Painting
          </Html>
        </mesh>
        <mesh
          geometry={nodes.bottle2_Material008_0.geometry}
          material={materials["Material.008"]}
          position={[32.4, 74.81, 164.09]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={4.66}
        />
        <mesh
          geometry={nodes.table_Material011_0.geometry}
          material={materials["Material.011"]}
          position={[22.44, 36.22, 177.32]}
          rotation={[0, -1.5, 1.57]}
          scale={[28.77, 20.81, 33.74]}
        />
        <mesh
          onPointerEnter={() => setHovered(true)}
          onPointerLeave={() => setHovered(false)}
          geometry={nodes.sofa_Soft_Black_Fabric_0.geometry}
          material={materials.Soft_Black_Fabric}
          position={[-84.42, 76.72, 90.03]}
          rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
          scale={[39.96, 73.88, 24.62]}
        >
          <Html prepend wrapperClass="sofa">
            Sofa
          </Html>
        </mesh>
        <mesh
          geometry={nodes.piping_Soft_Black_Fabric001_0.geometry}
          material={materials["Soft_Black_Fabric.001"]}
          position={[-75.16, 62.07, -2.55]}
          rotation={[-Math.PI, -Math.PI / 6, -Math.PI / 2]}
          scale={[28.38, 52.06, 18.74]}
        />
        <mesh
          geometry={nodes.carpet_Fabric_Upholstery_001a_0.geometry}
          material={materials.Fabric_Upholstery_001a}
          position={[-16.96, 3.8, 55.58]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[-223.06, 223.06, 3.39]}
        />
        <mesh
          geometry={nodes.bottle1_Material007_0.geometry}
          material={materials["Material.007"]}
          position={[28.42, 81.05, 181.48]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={10.66}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/apart-transformed.glb");
